language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
git:
  depth: 1
install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install -r requirements_dev.txt
  - pip3 install .
script:
  - if [ "$TRAVIS_BRANCH" = "dev" ]; then python3 -m pytest tests/ -m "not benchmark" || python -m pytest tests/ -m "not benchmark"; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then python3 -m pytest tests/ || python -m pytest tests/; fi